# Generated by Django 5.0.6 on 2024-06-25 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_categoria"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categoria",
            new_name="Acessorio",
        ),
    ]
