# Generated by Django 5.0.6 on 2024-07-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_veiculo"),
    ]

    operations = [
        migrations.AddField(
            model_name="marca",
            name="nacionalidade",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
